# Site settings
title: LEVANTE
email: mcfrank@stanford.edu
description: >
  The LEVANTE Project -- Documentation and Tutorials
lang: en-US

baseurl: ""  # the subpath of your site
url: https://levante-temp.github.io/ # the base hostname & protocol for your site
git_address: http://github.com/levante-temp/levante-temp.github.io
git_edit_address: http://github.com/levante-temp/levante-temp.github.io/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: cosmo

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:

- scope:
    path: _docs
    type: docs
  values:
    layout: docs_no_navbar
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true

